### ISSUE TITLE
[Error]TesorFlow image_recongnition.py

### ISSUE THREAD

**Issue by Dhivin** [qboticslabs/ros_robotics_projects#2]
[libprotobuf ERROR google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
Traceback (most recent call last):
  File "image_recognition.py", line 48, in <module>
    tensor = RosTensorFlow()
  File "image_recognition.py", line 15, in __init__
    classify_image.create_graph()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/imagenet/classify_image.py", line 141, in create_graph
    graph_def.ParseFromString(f.read())
I get this error when i run the Ros-tesnorflow example.

**Comment by qboticslabs** [comment]
Hi @Dhivin 
The problem seems to be with TensorFlow. There is a discussion happening about this issue in the following GitHub thread. I have tested this code in " TensorFlow with CPU support only". 

https://github.com/tensorflow/tensorflow/issues/582

**Comment by Dhivin** [comment]
sudo pip install --force-reinstall --upgrade protobuf

Worked for me .

Thanks anyway.

**Comment by qboticslabs** [comment]
That's great :), so one of the working solution is 

**$ sudo pip install --force-reinstall --upgrade protobuf**
